Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub Owner Name
  GitHubToken:
    Type: String
    Description: GitHub Token
  Repository:
    Type: String
    Description: GitHub Repository
  Branch:
    Type: String
    Description: GitHub Branch
  ServiceName:
    Description: Name for the service
    Type: String
    AllowedPattern: "[-_ a-zA-Z0-9]*"
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes
      and underscores.
  CodePipelineArtifactStoreBucket:
    Type: String
  CodePipelineRoleArn:
    Type: String
  CodeBuildRoleArn:
    Type: String
  CodeBuildImage:
    Type: String
    Default: "aws/codebuild/nodejs:7.0.0"
    Description: Image used for CodeBuild project.
Resources:
  CodeBuildProject:
    Description: Creating AWS CodeBuild project
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub Building stage for ${Branch}.
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: Branch
            Value: !Ref Branch
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      Name: !Sub ${ServiceName}-${Branch}-build
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5
  ProjectPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref CodePipelineArtifactStoreBucket
        Type: S3
      Name: !Sub ${ServiceName}-${Branch}-Pipeline
      RestartExecutionOnUpdate: false
      RoleArn:
        Ref: CodePipelineRoleArn
      Stages:
        - 
          Name: Source
          Actions:
            - 
              Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - 
                  Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repository
                Branch: !Ref Branch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: CodeBuild
              InputArtifacts:
                -
                  Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              OutputArtifacts:
                -
                  Name: CodebuildOutput
              RunOrder: 1